[package]
name = "kodegen_tools_sequential_thinking"
version.workspace = true
edition = "2024"
description = "KODEGEN.ᴀɪ: Memory-efficient, Blazing-Fast, MCP tools for code generation agents."
authors = ["KODEGEN.ᴀɪ"]
homepage = "https://kodegen.ai"
repository = "https://github.com/cyrup-ai/kodegen"
readme = "../../README.md"
categories = ["development-tools", "command-line-utilities", "api-bindings"]
keywords = [
    "mcp",
    "terminal",
    "agent",
    "filesystem",
    "claude"
]
license = "Apache-2.0 OR MIT"

[dependencies]
kodegen_mcp_tool = { path = "../mcp-tool" , version = "0.0.1" }
kodegen_mcp_schema = { path = "../mcp-schema", version = "0.0.1" }

# MCP SDK - for Tool implementation and prompt types
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "schemars", "server", "transport-child-process", "transport-io", "transport-sse-client", "transport-sse-client-reqwest", "transport-streamable-http-client", "transport-streamable-http-client-reqwest"], version = "0.8.1" }

# Async runtime - for tokio::sync::RwLock
tokio = { version = "1.48", features = ["full"] }

# Serialization - for Args and responses
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Schema generation - for JsonSchema derive
schemars = "1.0"

# Error handling - for anyhow::anyhow! macro
anyhow = "1.0"

# Logging - for log::debug! macro
log = "0.4"

# Synchronization primitives - for Arc<RwLock<ThinkingState>>
parking_lot = "0.12.5"

# Terminal colors - for formatted stderr output
cyrup_termcolor = "2.0"

# Cross-platform paths - for XDG config directory resolution
dirs = "6.0"

# UUID generation - for unique session IDs
uuid = { version = "1.18", features = ["serde", "v4"] }
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

[lib]
name = "kodegen_tools_sequential_thinking"
path = "src/lib.rs"
