[package]
name         = "kodegen_daemon"
version.workspace = true
edition      = "2024"
license      = "Apache-2.0 OR MIT"

[dependencies]
anyhow               = "1"
chrono               = { version = "0.4", features = ["serde"] }
crossbeam-channel    = "0.5"
env_logger           = "0.11"
log                  = "0.4"
nix                  = { version = "0.30", default-features = false, features = ["fs", "process", "signal", "user"] }
once_cell            = "1"          # one‑time global config
serde                = { version = "1", features = ["derive"] }
serde_json           = "1"
toml                 = "0.9"
clap         = { version = "4.5", features = ["derive"] }   # for the new CLI
which        = "8"                                         # locate system executables
exec = "0.3.1"
dirs = "6.0.0"
thiserror   = "2.0.17"
cfg-if      = "1.0.4"
base64      = "0.22.1"
flate2      = { version = "1.1.4", default-features = false, features = ["rust_backend"] }
async-recursion = "1.1.1"

# Auto-configuration support
kodegen_bundler_autoconfig = { path = "../bundler-autoconfig" , version = "0.0.1" }

kodegen_tools_config = { path = "../tools-config" , version = "0.0.1" }
kodegen_utils = { path = "../utils" , version = "0.0.1" }

# Plugin system support
extism = "1.12"
oci-client = "0.15"

# async support (always enabled)
async-process = { version = "2.5" }
tokio         = { version = "1.48.0", features = ["process", "macros", "signal", "rt-multi-thread", "time", "fs"] }

# SSE server dependencies (always enabled)
axum          = { version = "0.8.6" }
tower         = { version = "0.5" }
tower-http    = { version = "0.6", features = ["cors", "trace"] }
reqwest       = { version = "0.12", features = ["json"] }
regex         = { version = "1.12.2" }
url           = { version = "2.5.7" }
uuid          = { version = "1.18", features = ["v4"] }
cyrup_termcolor = "2.0"
async-stream  = { version = "0.3" }
futures-util  = { version = "0.3" }
serde_urlencoded = { version = "0.7" }
rcgen = "0.14"
futures = "0.3.31"
time = { version = "0.3", features = ["macros", "serde"] }
tokio-stream = "0.1.17"
pem = "3.0"
x509-parser = "0.18"
p256 = { version = "0.13", features = ["ecdsa", "pem"] }
sha2 = "0.10"

# Zero-allocation performance optimizations
arrayvec = { version = "0.7", features = ["serde"] }          # Fixed-size arrays without heap allocation
memmap2 = { version = "0.9" }           # Memory-mapped file I/O for zero-copy access
atomic-counter = { version = "1.0" }    # Lock-free atomic counters
tokio-util = { version = "0.7" }        # Tokio utilities for cancellation
dashmap = { version = "6.1" }           # Lock-free concurrent hash maps
memchr = { version = "2.7" }            # SIMD-accelerated string matching
fastrand = "2.3.0"
jwalk = "0.8.1"
rayon = "1.11.0"
walkdir = "2.5.0"
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

[features]
default = []
systemd-notify = ["systemd"]
systemd = ["dep:systemd"]

# platform-specific deps
[target.'cfg(target_os = "linux")'.dependencies]
users = "0.11.0"
systemd = { version = "0.10", optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
winapi  = { version = "0.3", features = ["processthreadsapi", "winnt", "handleapi", "securitybaseapi"] }
windows = { version = "0.62", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Services",
  "Win32_System_Threading",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging"
] }

[target.'cfg(target_os = "macos")'.dependencies]
plist  = "1.8.0"
zip    = { version = "6.0", default-features = false, features = ["aes-crypto", "bzip2", "deflate64", "deflate", "time", "zstd"] }

[build-dependencies]
pkg-config = "0.3.32"
cc = "1.2"
tempfile = "3.23"
which = "8.0"
zip = { version = "6.0", default-features = false, features = ["aes-crypto", "bzip2", "deflate64", "deflate", "time", "zstd"] }
plist = "1.8.0"
# Dependencies needed for build scripts
jwalk = "0.8.1"
rayon = "1.11.0"
fastrand = "2.3.0"

[[bin]]
name = "kodegend"
path = "src/main.rs"
