
[package]
name = "kodegen_tools_citescrape"
authors = ["David Maple <david@kodegen.ai>"]
description = "A web crawler and scraper with AI-powered capabilities"
edition = "2024"
repository = "https://github.com/cyrup-ai/kodegen"
version.workspace = true
license = "Apache-2.0 OR MIT"

[dependencies]
log = "0.4.28"
env_logger = "0.11"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
cyrup_termcolor = "2.0"
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.17"
futures = "0.3.31"
futures-util = "0.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
anyhow = "1.0.100"
lru = "0.16"

# MCP tool dependencies
kodegen_mcp_tool = { path = "../mcp-tool" , version = "0.1.8" }
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "schemars", "server", "transport-child-process", "transport-io", "transport-sse-client", "transport-sse-client-reqwest", "transport-streamable-http-client", "transport-streamable-http-client-reqwest"], version = "0.8.1" }
schemars = "1.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.18.1", features = ["v4", "serde"] }
html-escape = "0.2.13"
regex = "1.12.2"
reqwest = { version = "0.12.24", features = ["json", "rustls-tls"] }
chromiumoxide = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main", features = ["tokio-runtime", "bytes", "_fetcher-native-tokio"], default-features = false }
chromiumoxide_cdp = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main" }
chromiumoxide_types = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main" }
scraper = "0.24.0"
ego-tree = "0.10.0"
kuchiki = "0.8"
lol_html = "2.7"
lazy_static = "1.5"
rand = "0.9.2"
hex = "0.4"
sanitize-filename = "0.6.0"
imstr = "0.2"
imurl = { git = "https://github.com/cyrup-ai/imurl" }
url = "2.5.7"
html2md = "0.2"
flate2 = "1.1"
convert_case = "0.8"
tempfile = "3.23.0"
xxhash-rust = { version = "0.8", features = ["xxh3"] }
base64 = "0.22"
pathdiff = "0.2"
crossbeam-channel = "0.5.15"
crossbeam-deque = "0.8.6"
crossbeam-queue = "0.3.12"
dirs = "6.0"
futures-core = "0.3.31"
futures-executor = "0.3.31"

# Search indexing
tantivy = "0.25"
jwalk = "0.8"
smallvec = "1.15"
smallstr = "0.3"
arrayvec = "0.7"
ahash = "0.8"
dashmap = "6.1"
num_cpus = "1.17"
parking_lot = "0.12"
once_cell = "1.21"
crossbeam-utils = "0.8"
rayon = "1.11"
bloomfilter = "3.0"
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[dev-dependencies]
assert_fs = "1.1.3"
mockito = "1.7.0"
proptest = "1.8"

[features]
default = ["mirror"]
focus = []
mirror = []
present-progressive = []

[lib]
name = "kodegen_tools_citescrape"
path = "src/lib.rs"

[[example]]
name = "crawl_ratatui"
path = "examples/crawl_ratatui.rs"
