[package]
name = "kodegen_tools_prompt"
version.workspace = true
edition = "2024"
description = "KODEGEN.ᴀɪ: Memory-efficient, Blazing-Fast, MCP tools for code generation agents."
authors = ["KODEGEN.ᴀɪ"]
homepage = "https://kodegen.ai"
repository = "https://github.com/cyrup-ai/kodegen"
readme = "../../README.md"
categories = ["development-tools", "command-line-utilities", "api-bindings"]
keywords = [
    "mcp",
    "terminal",
    "agent",
    "filesystem",
    "claude"
]
license = "Apache-2.0 OR MIT"

[dependencies]
kodegen_mcp_tool = { path = "../mcp-tool" , version = "0.0.1" }

# MCP SDK - for Tool implementation
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "schemars", "server", "transport-child-process", "transport-io", "transport-sse-client", "transport-sse-client-reqwest", "transport-streamable-http-client", "transport-streamable-http-client-reqwest"], version = "0.8.1" }

# Async runtime - for async execute methods
tokio = { version = "1.48", features = ["full"] }

# Serialization - for Args and responses
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Schema generation - for JsonSchema derive
schemars = "1.0"

# Error handling - for error conversion and context
anyhow = "1.0"

# Template engine - CORE for rendering prompts with variables
minijinja = "2.12"

# Frontmatter parsing - CORE for parsing .j2.md file metadata
gray_matter = "0.3"

# Cross-platform paths - for finding prompts directory
dirs = "6.0"

# Logging - for debug/info/warn macros in manager and defaults
log = "0.4"
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

[lib]
name = "kodegen_tools_prompt"
path = "src/lib.rs"
