[package]
name        = "kodegen_tools_git"
version.workspace = true
edition     = "2024"
authors     = ["David Maple <david@kodegen.ai>"]
description = "Git CLI–like façade over the gix (Gitoxide) library"
license = "Apache-2.0 OR MIT"

[dependencies]
kodegen_mcp_schema = { path = "../mcp-schema" }
kodegen_mcp_tool = { path = "../mcp-tool" , version = "0.0.1" }
kodegen_utils = { path = "../utils" , version = "0.0.1" }
kodegen_tools_config = { path = "../tools-config", version = "0.0.1" }
kodegen_mcp_server_core = { path = "../mcp-server-sse" }
schemars = "1.0"
anyhow = "1.0"
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "schemars", "server", "transport-sse-server", "transport-child-process", "transport-io", "transport-sse-client", "transport-sse-client-reqwest", "transport-streamable-http-client", "transport-streamable-http-client-reqwest"], version = "0.8.1" }

gix         = { version = "0.74", default-features = false, features = [
    "blocking-network-client",
    "max-performance",
    "credentials",
    "revision",
    "index",
    "blob-diff",
    "worktree-mutation",
    "merge",
    "excludes",
    "status",
] }
thiserror   = "2.0.17"
chrono      = "0.4"
log         = "0.4"
tokio       = { version = "1.48", features = ["rt", "rt-multi-thread", "macros", "sync", "fs"] }
tokio-stream = "0.1"
futures     = "0.3"
serde       = { version = "1.0", features = ["derive"] }
serde_json  = "1.0"
walkdir     = "2.5"
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

[dev-dependencies]
tempfile    = "3.23"

[lib]
name = "kodegen_tools_git"
path = "src/lib.rs"

[[bin]]
name = "kodegen-git"
path = "src/main.rs"
