[package]
name = "kodegen_mcp_client"
version.workspace = true
edition = "2024"
description = "MCP client for kodegen server integration testing"
license = "Apache-2.0 OR MIT"

[dependencies]
# MCP SDK with client features
rmcp = { version = "0.8", git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "transport-child-process", "transport-sse-client-reqwest", "transport-streamable-http-client-reqwest"] }

# Async runtime
tokio = { version = "1.48", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "2.0"

# Logging (for examples)
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
chrono = { version = "0.4", features = ["serde"] }

# Process management (for cleanup on error in examples)
sysinfo = "0.37"
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

[dev-dependencies]
tempfile = "3.23"  # For filesystem test fixtures
kodegen_tools_database = { path = "../tools-database", version = "0.0.1" }
