[package]
name = "kodegen_tools_config"
version.workspace = true
edition = "2024"
description = "KODEGEN.ᴀɪ: Memory-efficient, Blazing-Fast, MCP tools for code generation agents."
authors = ["KODEGEN.ᴀɪ"]
homepage = "https://kodegen.ai"
repository = "https://github.com/cyrup-ai/kodegen"
readme = "../../README.md"
categories = ["development-tools", "command-line-utilities", "api-bindings"]
keywords = [
    "mcp",
    "terminal",
    "agent",
    "filesystem",
    "claude"
]
license = "Apache-2.0 OR MIT"

[dependencies]
kodegen_mcp_tool = { path = "../mcp-tool" , version = "0.0.1" }
kodegen_mcp_schema = { path = "../mcp-schema", version = "0.0.1" }
kodegen_utils = { path = "../utils" , version = "0.0.1" }

# MCP SDK - for Tool implementation and SSE server (manual due to circular dependency with mcp-server-core)
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "schemars", "server", "transport-sse-server"], version = "0.8.1" }

# Dependencies for manual SSE server (can't use mcp-server-core due to circular dependency)
clap = { version = "4.5", features = ["derive"] }
axum-server = { version = "0.7", features = ["tls-rustls"] }
tokio-util = "0.7"
env_logger = "0.11"
log = "0.4"
rustls = "0.23"

# Async runtime
tokio = { version = "1.48", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Schema generation
schemars = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "2.0"

# Process management
sysinfo = "0.37"

# String manipulation and search
regex = "1.12"
grep = "0.4"           # Ripgrep library for fast line-oriented regex searching
ignore = "0.4.24"      # Directory walking with .gitignore support

# Cross-platform compatibility
dirs = "6.0"

# Template engine and frontmatter parsing
minijinja = "2.12"
gray_matter = "0.3"

# HTTP for potential future features
reqwest = { version = "0.12", features = ["json"] }

# Date/time
chrono = { version = "0.4", features = ["serde"] }

# Async utilities
futures = "0.3"

# Base64 encoding/decoding
base64 = "0.22.1"

mime_guess = "2.0.5"
once_cell = "1.21.3"
parking_lot = "0.12.5"
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

[lib]
name = "kodegen_tools_config"
path = "src/lib.rs"

[[bin]]
name = "kodegen-config"
path = "src/main.rs"
