# Nextest configuration for citescrape test suite

[profile.default]
# Run tests in parallel
test-threads = "num-cpus"

# How long to wait for a test to finish
slow-timeout = { period = "60s", terminate-after = 2 }

# Default timeout for tests
default-timeout = "30s"

# Retry failed tests
retries = { backoff = "exponential", count = 2, delay = "1s" }

# Status level for tests
status-level = "pass"

# Failure output
failure-output = "immediate"

# Success output  
success-output = "never"

[profile.ci]
# CI-specific settings
test-threads = 4
slow-timeout = { period = "120s", terminate-after = 2 }
retries = { backoff = "exponential", count = 3, delay = "5s" }

[test-groups]
# Group browser tests separately as they may be slower
browser = { max-threads = 2 }

[[profile.default.overrides]]
filter = "test(browser_)"
test-group = "browser"

[[profile.default.overrides]]
# Integration tests may take longer
filter = "test(integration_)"
slow-timeout = { period = "120s", terminate-after = 2 }

[[profile.default.overrides]]
# Performance tests need more time
filter = "test(performance_)"
slow-timeout = { period = "180s", terminate-after = 1 }