[package]
name = "kodegen_tools_terminal"
version.workspace = true
edition = "2024"
description = "KODEGEN.ᴀɪ: Memory-efficient, Blazing-Fast, MCP tools for code generation agents."
license = "Apache-2.0 OR MIT"
authors = ["KODEGEN.ᴀɪ"]
homepage = "https://kodegen.ai"
repository = "https://github.com/cyrup-ai/kodegen"
readme = "../../README.md"
categories = ["development-tools", "command-line-utilities", "api-bindings"]
keywords = [
    "mcp",
    "terminal", 
    "agent",
    "filesystem",
    "claude"
]

[dependencies]
kodegen_mcp_schema = { path = "../mcp-schema" }
kodegen_mcp_tool = { path = "../mcp-tool" , version = "0.0.1" }
kodegen_tools_config = { path = "../tools-config", version = "0.0.1" }
kodegen_utils = { path = "../utils", version = "0.0.1" }

# MCP SDK - for Tool implementation and SSE server
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "schemars", "server", "transport-sse-server", "transport-child-process", "transport-io", "transport-sse-client", "transport-sse-client-reqwest", "transport-streamable-http-client", "transport-streamable-http-client-reqwest"], version = "0.8.1" }

# CLI argument parsing - for binary
clap = { version = "4.5", features = ["derive"] }

# TLS/HTTPS - for binary
rustls = { version = "0.23", features = ["ring"] }

# HTTP server - for binary SSE server
axum-server = { version = "0.7", features = ["tls-rustls"] }

# Cancellation tokens - for graceful shutdown
tokio-util = "0.7"

# Logging initialization - for binary
env_logger = "0.11"

# Async runtime - for process management, IO, sync primitives
tokio = { version = "1.48", features = ["full"] }

# Serialization - for Args and responses
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Schema generation - for JsonSchema derive
schemars = "1.0"

# Synchronization primitives - for managers' state management
parking_lot = "0.12.5"

# Pattern matching - for command validation and REPL prompt detection
regex = "1.12"

# Timestamps - for session tracking
chrono = { version = "0.4", features = ["serde"] }

# Logging - for debug/error/warn/info in managers
log = "0.4"

# Error handling - for error conversion in terminal_manager
anyhow = "1.0"

# PTY and VT100 terminal emulation dependencies (from cyterm)
bytes = "1.10"
portable-pty = "0.9"
tokio-stream = "0.1"
vt100 = "0.16"
uuid = { version = "1.18", features = ["serde", "v4"] }
once_cell = "1.21"
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[lib]
name = "kodegen_tools_terminal"
path = "src/lib.rs"

[[bin]]
name = "kodegen-terminal"
path = "src/main.rs"
