[package]
name = "tools-browser"
version = "0.1.0"
edition = "2024"

[workspace]

[lib]
name = "tools_browser"

[dependencies]
kodegen-mcp-tool = { path = "../mcp-tool" }
rmcp = { path = "../mcp-client" }
schemars = { version = "0.8", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chromiumoxide = { version = "0.5", features = ["tokio-runtime"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
reqwest = { version = "0.11", features = ["json"] }
anyhow = "1.0"
async-trait = "0.1"
tracing = "0.1"
base64 = "0.22"
