[package]
name = "kodegen_tools_browser"
authors = ["David Maple <david@kodegen.ai>"]
description = "Browser automation tools for AI agents"
edition = "2024"
repository = "https://github.com/cyrup-ai/kodegen"
version.workspace = true
license = "Apache-2.0 OR MIT"

[lib]
name = "kodegen_tools_browser"
crate-type = ["lib"]

[dependencies]
# MCP tool dependencies
kodegen_mcp_schema = { path = "../mcp-schema" }
kodegen_mcp_tool = { path = "../mcp-tool", version = "0.0.1" }
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "schemars", "server"] }
schemars = "1.0"

# Async runtime
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.17"
futures = "0.3.31"
futures-util = "0.3"
async-trait = "0.1"

# Browser automation (CRITICAL: must use git dependency)
chromiumoxide = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main", features = ["tokio-runtime", "bytes", "_fetcher-native-tokio"], default-features = false }
chromiumoxide_cdp = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main" }
chromiumoxide_types = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main" }

# Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
base64 = "0.22"

# Error handling
thiserror = "2.0.17"
anyhow = "1.0.100"

# Logging
log = "0.4.28"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

# HTTP client
reqwest = { version = "0.12.24", features = ["json", "rustls-tls"] }

# Utilities
dirs = "6.0"
parking_lot = "0.12"
once_cell = "1.21"
rand = "0.9.2"

# LLM infrastructure (workspace package)
kodegen_candle_agent = { path = "../tools-candle-agent", version = "0.1.0", optional = true }
cyrup_sugars = { git = "https://github.com/cyrup-ai/cyrup-sugars", branch = "main", package = "cyrup_sugars", features = ["all"], optional = true }

# MCP client for calling existing tools (HOT PATH!)
kodegen_mcp_client = { path = "../mcp-client", version = "0.0.1", optional = true }

# Time/date (required by deep_research.rs, agent/mod.rs)
chrono = { version = "0.4", features = ["serde"], optional = true }

# URL encoding (required by deep_research.rs:77)
urlencoding = { version = "2.1", optional = true }

# YAML config parsing
serde_yaml = "0.9"

# Plugin system (required by pdk.rs:1)
extism-pdk = { version = "1.0", optional = true }

workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

[features]
default = ["basic"]
basic = []
agent = ["kodegen_candle_agent", "cyrup_sugars", "kodegen_mcp_client", "chrono"]
research = ["agent", "urlencoding"]
pdk = ["extism-pdk"]
full = ["agent", "research", "pdk"]
