[package]
name = "kodegen_tools_browser"
authors = ["David Maple <david@kodegen.ai>"]
description = "Browser automation tools for AI agents"
edition = "2024"
repository = "https://github.com/cyrup-ai/kodegen"
version.workspace = true
license = "Apache-2.0 OR MIT"

[lib]
name = "kodegen_tools_browser"
crate-type = ["lib"]

[dependencies]
# MCP tool dependencies
kodegen_mcp_tool = { path = "../mcp-tool", version = "0.0.1" }
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "schemars", "server"] }
schemars = "1.0"

# Async runtime
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = "0.1.17"
futures = "0.3.31"
futures-util = "0.3"
async-trait = "0.1"

# Browser automation (CRITICAL: must use git dependency)
chromiumoxide = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main", features = ["tokio-runtime", "bytes", "_fetcher-native-tokio"], default-features = false }
chromiumoxide_cdp = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main" }
chromiumoxide_types = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main" }

# Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
base64 = "0.22"

# Error handling
thiserror = "2.0.17"
anyhow = "1.0.100"

# Logging
log = "0.4.28"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"

# HTTP client
reqwest = { version = "0.12.24", features = ["json", "rustls-tls"] }

# Utilities
dirs = "6.0"
parking_lot = "0.12"
once_cell = "1.21"
rand = "0.9.2"

# Clipboard support (used by controller)
arboard = "3.4"

workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }
