# https://docs.rs/cargo-hakari/latest/cargo_hakari/config

hakari-package = "workspace-hack"
dep-format-version = "4"
resolver = "3"

[final-excludes]
third-party = [
    { name = "float8" },
    { name = "cudarc" },
    { name = "bindgen_cuda" },
    { name = "half" },
    { name = "metal" },
    { name = "accelerate-src" },
    { name = "intel-mkl-src" },
]