# https://docs.rs/cargo-hakari/latest/cargo_hakari/config

hakari-package = "workspace-hack"
dep-format-version = "4"
resolver = "3"

[final-excludes]
third-party = [
    # Candle ML framework (already excluded)
    { name = "candle-core", version = ">=0.9.2-alpha.1" },
    { name = "candle-nn", version = ">=0.9.2-alpha.1" },
    { name = "candle-transformers", version = ">=0.9.2-alpha.1" },
    { name = "candle-metal-kernels", version = ">=0.9.2-alpha.1" },
    { name = "candle-kernels", version = ">=0.9.2-alpha.1" },
    { name = "float8" },
    { name = "cudarc", version = ">=0.17.3" },
    { name = "bindgen_cuda", version = ">=0.1.5"},
    { name = "half" },
    { name = "metal" },
    { name = "accelerate-src" },
    { name = "intel-mkl-src" },
    { name = "ug-cuda" },
    { name = "tokenizers" },
    
    # GitHub API (tools-github only)
    { name = "octocrab" },
    { name = "jsonwebtoken" },
    { name = "snafu" },
    
    # Database (tools-database only)
    { name = "sqlx" },
    { name = "sqlx-core" },
    { name = "sqlx-mysql" },
    { name = "sqlx-postgres" },
    { name = "sqlx-sqlite" },
    { name = "ssh2" },
    { name = "secrecy" },
    { name = "sqlparser" },
    
    # Search indexing (tools-citescrape only)
    { name = "tantivy" },
    { name = "jwalk" },
    { name = "smallvec" },
    { name = "smallstr" },
    { name = "arrayvec" },
    { name = "ahash" },
    { name = "dashmap" },
    { name = "bloomfilter" },
    
    # Terminal emulation (tools-terminal only)
    { name = "portable-pty" },
    { name = "vt100" },
    
    # HTML/Web scraping (tools-citescrape only)
    { name = "scraper" },
    { name = "kuchiki" },
    { name = "lol_html" },
    { name = "html-escape" },
    { name = "html2md" },
    { name = "ego-tree" },
    { name = "imstr" },
    
    # Citescrape specific
    { name = "sanitize-filename" },
    { name = "pathdiff" },
    { name = "xxhash-rust" },
    { name = "flate2" },
    { name = "convert_case" },
    
    # Crossbeam (citescrape, but also used elsewhere - check if safe to exclude)
    { name = "crossbeam-channel" },
    { name = "crossbeam-deque" },
    { name = "crossbeam-queue" },
    
    # Terminal-specific
    { name = "libc" },  # Unix only for terminal
    
    # Misc single-package dependencies
    { name = "semver" },  # github only
    { name = "lazy_static" },  # github, citescrape
    { name = "urlencoding" },  # browser optional
    
    # Git-related (gix is large, used only by git and github)
    { name = "gix" },
    { name = "gix-actor" },
    { name = "gix-hash" },
    { name = "gix-object" },
    { name = "gix-ref" },
    { name = "gix-config" },
    { name = "gix-tempfile" },
    { name = "gix-lock" },
    { name = "gix-date" },
    { name = "gix-validate" },
    { name = "gix-chunk" },
    { name = "gix-path" },
    { name = "gix-glob" },
    { name = "gix-quote" },
    { name = "gix-attributes" },
    { name = "gix-index" },
    { name = "gix-worktree" },
    { name = "gix-diff" },
    { name = "gix-traverse" },
    { name = "gix-revwalk" },
    { name = "gix-revision" },
    { name = "gix-refspec" },
    { name = "gix-submodule" },
    { name = "gix-bitmap" },
]
