# https://docs.rs/cargo-hakari/latest/cargo_hakari/config

hakari-package = "workspace-hack"
dep-format-version = "4"
resolver = "3"

[final-excludes]
third-party = [
    { name = "candle-core", version = ">=0.9.2-alpha.1" },
    { name = "candle-nn", version = ">=0.9.2-alpha.1" },
    { name = "candle-transformers", version = ">=0.9.2-alpha.1" },
    { name = "candle-metal-kernels", version = ">=0.9.2-alpha.1" },
    { name = "candle-kernels", version = ">=0.9.2-alpha.1" },
    { name = "float8" },
    { name = "cudarc" },
    { name = "bindgen_cuda" },
    { name = "half" },
    { name = "metal" },
    { name = "accelerate-src" },
    { name = "intel-mkl-src" },
    { name = "ug-cuda" },
]