[package]
name = "kodegen_mcp_tool"
version.workspace = true
edition = "2024"
description = "KODEGEN.ᴀɪ: Memory-efficient, Blazing-Fast, MCP tools for code generation agents."
license = "Apache-2.0 OR MIT"
authors = ["KODEGEN.ᴀɪ"]
homepage = "https://kodegen.ai"
repository = "https://github.com/cyrup-ai/kodegen"
readme = "../../README.md"
categories = ["development-tools", "command-line-utilities", "api-bindings"]
keywords = [
    "mcp",
    "terminal",
    "agent",
    "filesystem",
    "claude"
]

[dependencies]
# MCP SDK - for RMCP integration
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = [
    "client", 
    "schemars", 
    "server", 
    "transport-child-process", 
    "transport-io", 
    "transport-sse-client", 
    "transport-sse-client-reqwest", 
    "transport-streamable-http-client", 
    "transport-streamable-http-client-reqwest"
], version = "0.8.1" }

# Async runtime (for tool_history)
tokio = { version = "1.48", features = ["full"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Schema generation
schemars = "1.0"

# Error handling
thiserror = "2.0"
anyhow = "1.0"

# Synchronization primitives (for schema cache)
parking_lot = "0.12.5"

# Date/time (for tool_history)
chrono = { version = "0.4", features = ["serde"] }

# Terminal colors (for tool_history)
cyrup_termcolor = "2.0"

# Cross-platform paths (for tool_history)
dirs = "6.0"
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

[lib]
name = "kodegen_mcp_tool"
path = "src/lib.rs"
