[package]
name = "kodegen_bundler_sign"
version.workspace = true
edition = "2024"

[[bin]]
name = "kodegen_bundler_sign"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9"
dirs = "6.0"
shellexpand = "3.1"
rcgen = "0.14"
reqwest = { version = "0.12", features = ["json", "blocking"] }
jsonwebtoken = "9.3"
base64 = "0.22"
thiserror = "2.0"
tempfile = "3"

# File locking for keychain import synchronization
fs2 = "0.4"

# Random password generation for temporary p12 files
rand = "0.9"

# Secure memory clearing
zeroize = { version = "1", features = ["derive"] }

# Binary path finding for osslsigncode
which = "8.0"

# Certificate expiry date handling
chrono = { version = "0.4", features = ["serde"] }

# Terminal colors (REQUIRED for all user-facing output)
cyrup_termcolor = "2.0"

# Helper building and GitHub upload dependencies
cc = "1.2"                          # Compile C code for helper
zip = "6.0"                         # Create ZIP files
sha2 = "0.10"                       # Checksums
hex = "0.4"                         # Hex encoding
kodegen_tools_github = { path = "../tools-github" , version = "0.0.1" }  # GitHub API client (octocrab-based)
tokio = { version = "1.48", features = ["rt", "macros", "fs"] }  # Async runtime
bytes = "1.10"                       # For file upload
octocrab = "0.47"                   # GitHub API (for direct access to upload_asset)
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }
