[package]
name = "kodegen"
version.workspace = true
edition = "2024"
description = "KODEGEN.ᴀɪ: Memory-efficient, Blazing-Fast, MCP tools for code generation agents."
license = "Apache-2.0 OR MIT"
authors = ["KODEGEN.ᴀɪ"]
homepage = "https://kodegen.ai"
repository = "https://github.com/cyrup-ai/kodegen"
readme = "../../README.md"
categories = ["development-tools", "command-line-utilities", "api-bindings"]
keywords = [
    "mcp",
    "terminal",
    "agent",
    "filesystem",
    "claude"
]

[dependencies]
cyrup_termcolor = "2.0"

# Core packages - REQUIRED (always compiled)
kodegen_mcp_schema = { path = "../mcp-schema", version = "0.0.1" }  # For static tool metadata
kodegen_tools_config = { path = "../tools-config" , version = "0.0.1" }
kodegen_mcp_tool = { path = "../mcp-tool" , version = "0.0.1" }
kodegen_utils = { path = "../utils" , version = "0.0.1" }
kodegen_bundler_autoconfig = { path = "../bundler-autoconfig" , version = "0.0.1" }
kodegen_mcp_client = { path = "../mcp-client" , version = "0.0.1" }

# CLI argument parsing
clap = { version = "4.5", features = ["derive", "env"] }

# MCP SDK
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "schemars", "server", "transport-child-process", "transport-io", "transport-sse-client", "transport-sse-client-reqwest", "transport-sse-server", "transport-streamable-http-client", "transport-streamable-http-client-reqwest"], version = "0.8.1" }

# Async runtime
tokio = { version = "1.48", features = ["full"] }
tokio-util = "0.7"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Schema generation
schemars = "1.0"

# Error handling
anyhow = "1.0"

# Logging
log = "0.4"
env_logger = "0.11"

# Random number generation (for connection retry jitter)
rand = "0.9"

# Cross-platform compatibility
dirs = "6.0"
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

[features]
default = []

# Stdio server uses static metadata - no tool dependencies needed
# Tool filtering is done at runtime via --tool/--tools CLI args

[dev-dependencies]



[[bin]]
name = "kodegen"
path = "src/main.rs"
