[package]
name = "kodegen"
version.workspace = true
edition = "2024"
description = "KODEGEN.ᴀɪ: Memory-efficient, Blazing-Fast, MCP tools for code generation agents."
license = "Apache-2.0 OR MIT"
authors = ["KODEGEN.ᴀɪ"]
homepage = "https://kodegen.ai"
repository = "https://github.com/cyrup-ai/kodegen"
readme = "../../README.md"
categories = ["development-tools", "command-line-utilities", "api-bindings"]
keywords = [
    "mcp",
    "terminal",
    "agent",
    "filesystem",
    "claude"
]

[dependencies]
cyrup_termcolor = "2.0"

# Tool packages - OPTIONAL (only compiled when features are enabled)
kodegen_tools_filesystem = { path = "../tools-filesystem", optional = true , version = "0.1.8" }
kodegen_tools_terminal = { path = "../tools-terminal", optional = true , version = "0.1.8" }
kodegen_tools_process = { path = "../tools-process", optional = true , version = "0.1.8" }
kodegen_tools_introspection = { path = "../tools-introspection", optional = true , version = "0.1.8" }
kodegen_tools_prompt = { path = "../tools-prompt", optional = true , version = "0.1.8" }
kodegen_tools_sequential_thinking = { path = "../tools-sequential-thinking", optional = true , version = "0.1.8" }
kodegen_tools_claude_agent = { path = "../tools-claude-agent", optional = true , version = "0.1.8" }
kodegen_tools_citescrape = { path = "../tools-citescrape", optional = true , version = "0.1.8" }
kodegen_tools_git = { path = "../tools-git", optional = true , version = "0.1.8" }
kodegen_tools_github = { path = "../tools-github", optional = true , version = "0.1.8" }

# Core packages - REQUIRED (always compiled)
kodegen_tools_config = { path = "../tools-config" , version = "0.1.8" }
kodegen_mcp_tool = { path = "../mcp-tool" , version = "0.1.8" }
kodegen_utils = { path = "../utils" , version = "0.1.8" }
kodegen_bundler_autoconfig = { path = "../bundler-autoconfig" , version = "0.1.8" }
kodegen_mcp_client = { path = "../mcp-client" , version = "0.1.8" }

# CLI argument parsing
clap = { version = "4.5", features = ["derive", "env"] }

# MCP SDK
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "schemars", "server", "transport-child-process", "transport-io", "transport-sse-client", "transport-sse-client-reqwest", "transport-sse-server", "transport-streamable-http-client", "transport-streamable-http-client-reqwest"], version = "0.8.1" }

# Async runtime
tokio = { version = "1.48", features = ["full"] }
tokio-util = "0.7"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Schema generation
schemars = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "2.0"

# Logging
log = "0.4"
env_logger = "0.11"

# Process management
sysinfo = "0.37"

# Browser automation (for citescrape tools)
chromiumoxide = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main", features = ["tokio-runtime", "bytes", "_fetcher-native-tokio"], default-features = false }
chromiumoxide_cdp = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main" }
chromiumoxide_types = { git = "https://github.com/mattsse/chromiumoxide.git", branch = "main" }

# String manipulation and search
regex = "1.12"
grep = "0.4"           # Ripgrep library for fast line-oriented regex searching
ignore = "0.4.24"      # Directory walking with .gitignore support

# Random number generation
rand = "0.9"

# Cross-platform compatibility
dirs = "6.0"

# Template engine and frontmatter parsing
minijinja = "2.12"
gray_matter = "0.3"

# HTTP for potential future features
reqwest = { version = "0.12", features = ["json"] }

# TLS/HTTPS support for SSE server
axum-server = { version = "0.7", features = ["tls-rustls"] }
rustls = { version = "0.23", features = ["ring"] }

# Date/time
chrono = { version = "0.4", features = ["serde"] }

# Async utilities
futures = "0.3"

# Base64 encoding/decoding
base64 = "0.22.1"

mime_guess = "2.0.5"
once_cell = "1.21.3"
parking_lot = "0.12.5"
workspace-hack = { version = "0.1", path = "../../workspace-hack" }

[features]
default = ["all"]

# Meta-feature: enable everything
all = [
    "filesystem",
    "terminal",
    "process",
    "introspection",
    "prompt",
    "sequential_thinking",
    "claude_agent",
    "citescrape",
    "git",
    "github",
    "config"
]

# Individual tool categories (feature names EXACTLY match package names)
filesystem = ["dep:kodegen_tools_filesystem"]
terminal = ["dep:kodegen_tools_terminal"]
process = ["dep:kodegen_tools_process"]
introspection = ["dep:kodegen_tools_introspection"]
prompt = ["dep:kodegen_tools_prompt"]
sequential_thinking = ["dep:kodegen_tools_sequential_thinking"]
claude_agent = ["dep:kodegen_tools_claude_agent"]
citescrape = ["dep:kodegen_tools_citescrape"]
git = ["dep:kodegen_tools_git"]
github = ["dep:kodegen_tools_github"]
config = []  # Config tools (ConfigManager is always required by other tools)  

# Convenience feature sets
minimal = ["filesystem", "terminal"]
standard = ["filesystem", "terminal", "process", "prompt"]
advanced = ["all"]

[dev-dependencies]



[[bin]]
name = "kodegen"
path = "src/main.rs"
