[package]
name = "kodegen_bundler_autoconfig"
version.workspace = true
edition = "2024"
license = "Apache-2.0 OR MIT"
authors = ["David Maple <david.maple@cyrup.ai>"]

[dependencies]
watchexec = "8.0.1"
watchexec-filterer-globset = "8.0.0"
watchexec-events = "6.0.0"
watchexec-signals = "5.0.0"
miette = "7.6.0"

# Config file handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9"
serde_yaml = "0.9"

# Core utilities
anyhow = "1.0"
thiserror = "2.0"
log = "0.4"
tokio = { version = "1", features = ["full"] }
directories = "6.0.0"
crossbeam-channel = "0.5.15"
parking_lot = "0.12.5"
dashmap = "6.1"

# Plugin system
extism = "1.12.0"
extism-pdk = "1.4.1"
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

# Workspace hack

# Platform-specific features
[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"

[target.'cfg(target_os = "macos")'.dependencies]
plist = "1.8.0"

[lib]
name = "kodegen_bundler_autoconfig"
path = "src/lib.rs"


[features]
dirs = []
