[package]
name = "kodegen_tools_filesystem"
version.workspace = true
edition = "2024"
description = "KODEGEN.ᴀɪ: Memory-efficient, Blazing-Fast, MCP tools for code generation agents."
license = "Apache-2.0 OR MIT"
authors = ["KODEGEN.ᴀɪ"]
homepage = "https://kodegen.ai"
repository = "https://github.com/cyrup-ai/kodegen"
readme = "../../README.md"
categories = ["development-tools", "command-line-utilities", "api-bindings"]
keywords = [
    "mcp",
    "terminal",
    "agent",
    "filesystem",
    "claude"
]

[dependencies]
kodegen_mcp_schema = { path = "../mcp-schema" }
kodegen_mcp_tool = { path = "../mcp-tool" , version = "0.0.1" }
kodegen_tools_config = { path = "../tools-config" , version = "0.0.1" }
kodegen_utils = { path = "../utils" , version = "0.0.1" }

# SSE server core - for binary
kodegen_mcp_server_core = { path = "../mcp-server-sse" }

# MCP SDK - for Tool implementation
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk.git", branch = "main", features = ["client", "schemars", "server"], version = "0.8.1" }

# Async runtime - for file I/O operations
tokio = { version = "1.48", features = ["full"] }

# Serialization - for Args and responses
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Schema generation - for JsonSchema derive
schemars = "1.0"

# Error handling - for error conversion
anyhow = "1.0"

# Image encoding - CORE for read_file base64 encoding
base64 = "0.22.1"

# MIME type detection - CORE for read_file content type
mime_guess = "2.0.5"

# Search functionality - FULL ripgrep implementation
grep = "0.4"           # Core: regex matching, searcher, JSON printer
grep-pcre2 = "0.1.9"   # PCRE2 regex engine (always enabled)
globset = "0.4.18"     # Ripgrep's glob matching
regex = "1.12"
bstr = "1.12.0"         # Byte string utilities for ripgrep


# .gitignore support - CORE for directory walking with proper exclusions
ignore = "0.4.24"

# Async streams - for async search result streaming
futures = "0.3"

# Logging - for debug/error/info in filesystem operations
log = "0.4"
env_logger = "0.11"

# Date/time - for timestamps in edit logging
chrono = { version = "0.4", features = ["serde"] }

# HTTP client - for reading files from URLs
reqwest = { version = "0.12", features = ["json"] }

# Cross-platform paths - for home directory resolution
dirs = "6.0"

# Terminal colors - for formatted output in search tools
cyrup_termcolor = "2.0"

# UUID generation - for unique session IDs
uuid = { version = "1.18", features = ["serde", "v4"] }
workspace-hack = { version = "0.0.1", path = "../../workspace-hack" }

[dev-dependencies]
tempfile = "3.23"

[features]
default = []

[lib]
name = "kodegen_tools_filesystem"
path = "src/lib.rs"

[[example]]
name = "search_basics"
path = "examples/search_basics.rs"

[[example]]
name = "search_patterns"
path = "examples/search_patterns.rs"

[[example]]
name = "search_files"
path = "examples/search_files.rs"

[[example]]
name = "search_output"
path = "examples/search_output.rs"

[[example]]
name = "search_advanced"
path = "examples/search_advanced.rs"

[[bin]]
name = "kodegen-filesystem"
path = "src/main.rs"
